## Bar Charts

- A bar charts presents categorical data with rectangular bars with heights(or lengths) propotional to the values that they represent
- In general variables and data either represent measurements on some continious scale or they represent information about some categorical or discrete characteristics
- Using Bar Charts we can visualize categorical data.
- Typically the x-axis is the categoris and the y-axis is the count (number of occurrences) in each category
- However the y-axis can be any aggregation (count, sum, average,etc..)

In [1]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go

In [2]:
df = pd.read_csv('Data/2018WinterOlympics.csv')
df

    Rank                NOC  Gold  Silver  Bronze  Total
0      1             Norway    14      14      11     39
1      2            Germany    14      10       7     31
2      3             Canada    11       8      10     29
3      4      United States     9       8       6     23
4      5        Netherlands     8       6       6     20
5      6             Sweden     7       6       1     14
6      7  Republic of Korea     5       8       4     17
7      8        Switzerland     5       6       4     15
8      9             France     5       4       6     15
9     10            Austria     5       3       6     14
10    11              Japan     4       5       4     13
11    12              Italy     3       2       5     10
12    13                OAR     2       6       9     17
13    14     Czech Republic     2       2       3      7
14    15            Belarus     2       1       0      3
15    16              China     1       6       2      9
16    17           Slovakia     1       2       0      3
17    18            Finland     1       1       4      6
18    19      Great Britain     1       0       4      5
19    20             Poland     1       0       1      2
20    21            Hungary     1       0       0      1
21    21            Ukraine     1       0       0      1
22    23          Australia     0       2       1      3
23    24           Slovenia     0       1       1      2
24    25            Belgium     0       1       0      1
25    26              Spain     0       0       2      2
26    26        New Zealand     0       0       2      2
27    28         Kazakhstan     0       0       1      1
28    28             Latvia     0       0       1      1
29    28      Liechtenstein     0       0       1      1

In [3]:
data = [go.Bar(x=df['NOC'],y=df['Total'])]
layout = go.Layout(title='Medals')
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'

In [5]:
trace1 = go.Bar(x=df['NOC'],y=df['Gold'],name='Gold',marker={'color':'#FFD700'})
trace2 = go.Bar(x=df['NOC'],y=df['Silver'],name='Silver',marker={'color':'#9EA0A1'})
trace3 = go.Bar(x=df['NOC'],y=df['Bronze'],name='Bronze',marker={'color':'#CD7F32'})
data = [trace1,trace2,trace3]
layout = go.Layout(title='Medals')
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'

In [6]:
trace1 = go.Bar(x=df['NOC'],y=df['Gold'],name='Gold',marker={'color':'#FFD700'})
trace2 = go.Bar(x=df['NOC'],y=df['Silver'],name='Silver',marker={'color':'#9EA0A1'})
trace3 = go.Bar(x=df['NOC'],y=df['Bronze'],name='Bronze',marker={'color':'#CD7F32'})
data = [trace1,trace2,trace3]
layout = go.Layout(title='Medals',barmode='stack')
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'

In [23]:
df = pd.read_csv('Data/mocksurvey.csv')
df.head()

,Unnamed: 0,Strongly Agree,Somewhat Agree,Neutral,Somewhat Disagree,Strongly Disagree
0,Question 1,0.45,0.25,0.10,0.12,0.08
1,Question 2,0.12,0.07,0.48,0.18,0.15
2,Question 3,0.05,0.22,0.19,0.23,0.31

In [24]:
df = df.set_index(df.columns[0])
df.index.name = 'Questions'

In [25]:
print(df.columns.tolist())

['Strongly Agree', 'Somewhat Agree', 'Neutral', 'Somewhat Disagree', 'Strongly Disagree']

In [26]:
df.head()

,Strongly Agree,Somewhat Agree,Neutral,Somewhat Disagree,Strongly Disagree
Questions,,,,,
Question 1,0.45,0.25,0.10,0.12,0.08
Question 2,0.12,0.07,0.48,0.18,0.15
Question 3,0.05,0.22,0.19,0.23,0.31

In [29]:
df.index

Index(['Question 1', 'Question 2', 'Question 3'], dtype='object', name='Questions')

In [30]:
data = [go.Bar(x=df.index,y=df[response],name=response) for response in df.columns]

In [31]:
layout = go.Layout(title='Survey')
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'

In [32]:
layout = go.Layout(title='Survey',barmode='stack')
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'

In [35]:
data = [go.Bar(y=df.index,x=df[response],orientation='h',name=response) for response in df.columns]

In [36]:
layout = go.Layout(title='Survey',barmode='stack')
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'