## Heatmap
- Heatmap allow the visualization of 3 features.
- Categorical or continious features along the x anf y axis to amke up a grid and then a 3rd continious feature displayed through color
- We can also use categorical features on the x and y axis

In [1]:
import plotly.offline as pyo
import plotly.figure_factory as ff
import plotly.graph_objs as go
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/2010SantaBarbaraCA.csv')

In [3]:
df.head()

   LST_DATE      DAY LST_TIME  T_HR_AVG
0  20100601  TUESDAY     0:00      12.7
1  20100601  TUESDAY     1:00      12.7
2  20100601  TUESDAY     2:00      12.3
3  20100601  TUESDAY     3:00      12.5
4  20100601  TUESDAY     4:00      12.7

In [7]:
df.columns

Index(['LST_DATE', 'DAY', 'LST_TIME', 'T_HR_AVG'], dtype='object')

In [10]:
data = [go.Heatmap(x=df['DAY'],y=df['LST_TIME'],z=df['T_HR_AVG'].values.tolist(),colorscale='Jet')]
layout = go.Layout(title='SB CA Temps')
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [11]:
df = pd.read_csv('Data/2010YumaAZ.csv')
df

     LST_DATE      DAY LST_TIME  T_HR_AVG
0    20100601  TUESDAY     0:00      25.2
1    20100601  TUESDAY     1:00      24.1
2    20100601  TUESDAY     2:00      24.4
3    20100601  TUESDAY     3:00      24.9
4    20100601  TUESDAY     4:00      22.8
..        ...      ...      ...       ...
163  20100607   MONDAY    19:00      39.4
164  20100607   MONDAY    20:00      38.5
165  20100607   MONDAY    21:00      37.0
166  20100607   MONDAY    22:00      34.7
167  20100607   MONDAY    23:00      32.6

[168 rows x 4 columns]

In [12]:
data = [go.Heatmap(x=df['DAY'],y=df['LST_TIME'],z=df['T_HR_AVG'].values.tolist(),colorscale='Jet')]
layout = go.Layout(title='SB CA Temps')
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

## Multiple HEAT MAPS WITH SUBPLOTS

In [14]:
df1 = pd.read_csv('Data/2010SitkaAK.csv')
df2 = pd.read_csv('Data/2010SantaBarbaraCA.csv')
df3 = pd.read_csv('Data/2010YumaAZ.csv')


trace1 = go.Heatmap(x=df1['DAY'],y=df1['LST_TIME'],z=df1['T_HR_AVG'],colorscale='Jet',zmin=5,zmax=40)
trace2 = go.Heatmap(x=df2['DAY'],y=df2['LST_TIME'],z=df2['T_HR_AVG'],colorscale='Jet',zmin=5,zmax=40)
trace3 = go.Heatmap(x=df3['DAY'],y=df3['LST_TIME'],z=df3['T_HR_AVG'],colorscale='Jet',zmin=5,zmax=40)

In [15]:
from plotly import tools

In [18]:
fig = tools.make_subplots(rows=1,cols=3,subplot_titles=['Sitka AK','SB CA','Yuma AZ'],shared_yaxes=True)
fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)
fig.append_trace(trace3,1,3)
pyo.plot(fig)

'temp-plot.html'

In [19]:
fig = tools.make_subplots(rows=1,cols=3,subplot_titles=['Sitka AK','SB CA','Yuma AZ'],shared_yaxes=False)
fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)
fig.append_trace(trace3,1,3)
pyo.plot(fig)

'temp-plot.html'

In [21]:
fig = tools.make_subplots(rows=1,cols=3,subplot_titles=['Sitka AK','SB CA','Yuma AZ'],shared_yaxes=False)
fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)
fig.append_trace(trace3,1,3)
fig['layout'].update(title='Temps for 3 cities')
pyo.plot(fig)

'temp-plot.html'

In [23]:
df = pd.read_csv('Data/flights.csv')
df.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [24]:
data = [go.Heatmap(x=df['year'],y=df['month'],z=df['passengers'].values.tolist(),colorscale='Jet')]
layout = go.Layout(title='Flights')
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'